### PR TITLE
Fix/#39 channels sort

### LINKED ISSUE #39: Sorting of channels
Please sort the channels in the channel list in ascending order. Currently no sorting is in place. Thereby it is hard to find a channel.

### PR DESCRIPTION
**Pull request by vickyokrm**
1) Sort the rooms and channels list
2) Decouple Rooms and Login configuration
3) Store Login info even if the user not forwarded the email.
4) Fix linting

Closes #39 .

### CODE REVIEW

File: src/helper/login.js [hunk 1]
```diff
@@ -61,7 +61,16 @@ function getJoinedChannels(config, callback) {
...
+    var rooms = groups[0].groups.concat(channels[0].channels);
+    callback(rooms.sort(function(first,second) {
+      if ( first.name.toUpperCase() < second.name.toUpperCase() ){
+        return -1;
+      }
+      if ( first.name.toUpperCase() > second.name.toUpperCase() ){
+        return 1;
+      }
+      return 0;
+    }));
```
Comment (jschirrmacher) [inline src/helper/login.js:67]: try `localeCompare()`

Comment (vickyokrm) [reply src/helper/login.js:67]: Done!

**Review by jschirrmacher — APPROVED** [review]
